name: "Build base image"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
    paths:
      - "Dockerfile.base"
      - ".github/workflows/base-image.yml"
  workflow_dispatch:

jobs:
  build:
    name: "Build base image"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log versions
        run: |
          echo "Pydantic Core: ${{ vars.PYDANTIC_CORE_VERSION }}"
          echo "Pydantic : ${{ vars.PYDANTIC_VERSION }}"

      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: ghcr.io/nuvlaedge/ne-base:pydantic${{ vars.PYDANTIC_VERSION }}
          build-args: |
            PYDANTIC_CORE_VERSION=${{ vars.PYDANTIC_CORE_VERSION }}
            PYDANTIC_VERSION=${{ vars.PYDANTIC_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
