name: "Build base image"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
      - 'add-nuvlaedge-base-image'
    paths:
      - "Dockerfile.base"
  workflow_dispatch:

jobs:
  build:
    name: "Build base image"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build base image and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.base
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ghcr.io/nuvlaedge/ne-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
